on:
  workflow_call:

jobs:
  examples:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [11, 14, 17, 20, 23]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Configure
        run: cmake -S examples -B build/examples -G Ninja
          -D CMAKE_BUILD_TYPE:STRING=Release
          -D CMAKE_CXX_STANDARD:STRING=${{ matrix.version }}

      - name: Build
        run: cmake --build build/examples -j $(nproc)
