env:
  CTEST_OUTPUT_ON_FAILURE: 1

on:
  workflow_call:

jobs:
  gcc:
    name: gcc-${{ matrix.version }} (C++${{ matrix.standard }})

    strategy:
      fail-fast: false
      matrix:
        version: [11, 13]
        standard: [11, 14, 17, 20, 23]

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@master

      - name: Install GCC ${{ matrix.version }}
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt update
          sudo apt-get install -y gcc-${{ matrix.version }} g++-${{ matrix.version }}

      - name: Configure (install)
        run: cmake -S . -B build/install -G Ninja
          -D CMAKE_CXX_STANDARD:STRING=${{ matrix.standard }}
          -D CMAKE_BUILD_TYPE:STRING=Release
          -D CPP_LAZY_INSTALL:BOOL=ON
          -D CMAKE_INSTALL_PREFIX=build/prefix
          -D CMAKE_CXX_COMPILER=g++-${{ matrix.version }}

      - name: Build (install)
        run: cmake --build build/install -j $(nproc)

      - name: Install
        run: cmake --install build/install

      - name: Configure tests
        run: cmake -S tests -B build/tests -G Ninja
          -D CMAKE_BUILD_TYPE:STRING=Release
          -D TEST_INSTALLED_VERSION:BOOL=YES
          -D CMAKE_INSTALL_PREFIX=build/prefix
          -D CMAKE_CXX_STANDARD:STRING=${{ matrix.standard }}
          -D CMAKE_CXX_COMPILER=g++-${{ matrix.version }}

      - name: Build tests
        run: cmake --build build/tests -j $(nproc)

      - name: Run tests
        working-directory: build/tests
        run: ctest --output-on-failure -VV -j $(nproc)
